### ISSUE TITLE
0.1 roadmap

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/PSUtil.jl#1]
implement most psutil functionality for the Linux platform:

CPU:

- [x] [`cpu_times`](https://psutil.readthedocs.io/en/latest/#psutil.cpu_times) (7e5ade75ecdfaae60aea96f989199c6c31489ae1)
- [x] [`cpu_percent`](https://psutil.readthedocs.io/en/latest/#psutil.cpu_percent) (be69d118c411b1cd8ead2dcf6b934cd6dca77a19)
- [ ] [`cpu_times_percent`](https://psutil.readthedocs.io/en/latest/#psutil.cpu_times_percent)
- [x] [`cpu_count`](https://psutil.readthedocs.io/en/latest/#psutil.cpu_count) (be69d118c411b1cd8ead2dcf6b934cd6dca77a19)
- [ ] [`cpu_stats`](https://psutil.readthedocs.io/en/latest/#psutil.cpu_stats)
- [ ] [`cpu_freq`](https://psutil.readthedocs.io/en/latest/#psutil.cpu_freq)
- [ ] [`getloadavg`](https://psutil.readthedocs.io/en/latest/#psutil.getloadavg)

Memory:

- [ ] [`virtual_memory`](https://psutil.readthedocs.io/en/latest/#psutil.virtual_memory)
- [ ] [`swap_memory`](https://psutil.readthedocs.io/en/latest/#psutil.swap_memory)

Disks:

- [ ] [`disk_partitions`](https://psutil.readthedocs.io/en/latest/#psutil.disk_partitions)
- [ ] [`disk_usage`](https://psutil.readthedocs.io/en/latest/#psutil.disk_usage)
- [ ] [`disk_io_counters`](https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters)

Network:

- [ ] [`net_io_counters`](https://psutil.readthedocs.io/en/latest/#psutil.net_io_counters)
- [ ] [`net_connections`](https://psutil.readthedocs.io/en/latest/#psutil.net_connections)
- [ ] [`net_if_addrs`](https://psutil.readthedocs.io/en/latest/#psutil.net_if_addrs)
- [ ] [`net_if_stats`](https://psutil.readthedocs.io/en/latest/#psutil.net_if_stats)

Sensors:

- [ ] [`sensors_temperatures`](https://psutil.readthedocs.io/en/latest/#psutil.sensors_temperatures)
- [ ] [`sensors_fans`](https://psutil.readthedocs.io/en/latest/#psutil.sensors_fans)
- [ ] [`sensors_battery`](https://psutil.readthedocs.io/en/latest/#psutil.sensors_battery)

Other system info:

- [ ] [`boot_time`](https://psutil.readthedocs.io/en/latest/#psutil.boot_time)
- [ ] [`users`](https://psutil.readthedocs.io/en/latest/#psutil.users)

Processes:

- [ ] [`Process` class](https://psutil.readthedocs.io/en/latest/#process-class)
- [ ] [`pids`](https://psutil.readthedocs.io/en/latest/#psutil.pids)
- [ ] [`process_iter`](https://psutil.readthedocs.io/en/latest/#psutil.process_iter)
- [ ] [`pid_exists`](https://psutil.readthedocs.io/en/latest/#psutil.pid_exists)
